routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\PublishingHouseController;
use App\Models\Book;
use App\Models\Author;
use App\Models\PublishingHouse;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $books_count=Book::all()->count();
    $authors_count=Author::all()->count();
    $publishers_count=PublishingHouse::all()->count();
    return view('welcome', compact('books_count', 'authors_count', 'publishers_count'));
});

//Route::get('/', [IndexController::class, 'index']);

Route::resource('books', BookController::class);
Route::resource('authors', AuthorController::class);
Route::resource('publishers', PublishingHouseController::class);

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;
    protected $primaryKey = 'isbn';
    protected $fillable = ['isbn', 'title', 'year_of_publication', 'author_id', 'publisher_id'];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Book;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $book = Book::all();
        return view('books/index', compact('book'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $storeData = $request->validate([
            'title' => 'required|max:255',
            'isbn' => 'required|min:13|max:17|regex:/[0-9-]/i',
            'year_of_publication' => 'required|numeric',
            'author_id' => 'required|numeric',
            'publisher_id' => 'required|numeric'
        ]);
        $storeData['isbn'] = str_replace("-","",$request['isbn']); // trim is not working with dashes
        $book = Book::create($storeData);

        return redirect('/books')->with('completed', 'Book has been saved!')->setStatusCode(201);;
    }

    /**
     * Display the specified resource.
     *
     * @param  string  $isbn
     * @return \Illuminate\Http\Response
     */
    public function show($isbn)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  string  $isbn
     * @return \Illuminate\Http\Response
     */
    public function edit($isbn)
    {
        $book = Book::findOrFail($isbn);
        return view('books/edit', compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  string  $isbn
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $isbn)
    {
        $updateData = $request->validate([
            'title' => 'required|max:255',
            'isbn' => 'required|min:13|max:17|regex:/[0-9-]/i',
            'year_of_publication' => 'required|numeric',
            'author_id' => 'required|numeric',
            'publisher_id' => 'required|numeric'
        ]);
        $storeData['isbn'] = str_replace("-","",$request['isbn']); // trim is not working with dashes
        Book::where('isbn', $isbn)->update($updateData);
        return redirect('/books')->with('completed', 'Book has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  string  $isbn
     * @return \Illuminate\Http\Response
     */
    public function destroy($isbn)
    {
        $book = Book::where('isbn', $isbn)->firstOrFail();
        $book->delete();

        return redirect('/books')->with('completed', 'Book has been deleted');
    }
}

resources/views/books/create.blade.php
@extends('layout')

@section('content')

    <style>
        .container {
            max-width: 450px;
        }
        .push-top {
            margin-top: 50px;
        }
    </style>

    <div class="card push-top">
        <div class="card-header">
            Add Book
        </div>

        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form method="post" action="{{ route('books.store') }}">
                @csrf
                <div class="form-group">
                    <label for="isbn">ISBN</label>
                    <input type="text" class="form-control" name="isbn"/>
                </div>
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" name="title"/>
                </div>
                <div class="form-group">
                    <label for="year_of_publication">Year of publication</label>
                    <input type="number" class="form-control" name="year_of_publication"/>
                </div>
                <div class="form-group">
                    <label for="author_id">Author</label>
                    <input type="number" class="form-control" name="author_id"/>
                </div>
                <div class="form-group">
                    <label for="publisher_id">Publishing house</label>
                    <input type="number" class="form-control" name="publisher_id"/>
                </div>
                <button type="submit" class="btn btn-block btn-danger">Create Book</button>
            </form>
        </div>
    </div>
@endsection

resources/views/books/edit.blade.php
@extends('layout')

@section('content')

    <style>
        .container {
            max-width: 450px;
        }
        .push-top {
            margin-top: 50px;
        }
    </style>

    <div class="card push-top">
        <div class="card-header">
            Edit & Update
        </div>

        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form method="post" action="{{ route('books.update', $book->isbn) }}">
                @csrf
                @method('PATCH')
                <div class="form-group">
                    <label for="title">Name</label>
                    <input type="text" class="form-control" name="title" value = "{{$book->title}}"/>
                </div>
                <div class="form-group">
                    <label for="isbn">ISBN</label>
                    <input type="text" class="form-control" name="isbn" value = "{{$book->isbn}}"/>
                </div>
                <div class="form-group">
                    <label for="year_of_publication">Year of publication</label>
                    <input type="number" class="form-control" name="year_of_publication" value = "{{$book->year_of_publication}}"/>
                </div>
                <div class="form-group">
                    <label for="author_id">Author</label>
                    <input type="number" class="form-control" name="author_id" value = "{{$book->author_id}}"/>
                </div>
                <div class="form-group">
                    <label for="publisher_id">Publishing house</label>
                    <input type="number" class="form-control" name="publisher_id" value = "{{$book->publisher_id}}"/>
                </div>
                <button type="submit" class="btn btn-block btn-danger">Update Book</button>
            </form>
        </div>
    </div>
@endsection

resources/views/books/index.blade.php
@extends('layout')

@section('content')

    <style>
        .push-top {
            margin-top: 50px;
        }
    </style>

    <div class="push-top">
        @if(session()->get('completed'))
            <div class="alert alert-success">
                {{ session()->get('completed') }}
            </div><br />
        @endif
        @if($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
        @endif
        <table class="table">
            <thead>
            <tr class="table-warning">
                <td>ISBN</td>
                <td>Title</td>
                <td>Year of publication</td>
                <td>Author</td>
                <td>Publishing house</td>
                <td class="text-center">Action</td>
            </tr>
            </thead>
            <tbody>
            @foreach($book as $books)
                <tr>
                    <td>{{$books->isbn}}</td>
                    <td>{{$books->title}}</td>
                    <td>{{$books->year_of_publication}}</td>
                    <td>{{$books->author_id}}</td>
                    <td>{{$books->publisher_id}}</td>
                    <td class="text-center">
                        <a href="{{ route('books.edit', $books->isbn)}}" class="btn btn-primary btn-sm">Edit</a>
                        <form action="{{ route('books.destroy', $books->isbn)}}" method="post" style="display: inline-block">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('Are you sure?')">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
            <a href="{{ route('books.create') }}" class="btn btn-primary btn-sm">Create</a>
        <div>
@endsection