routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\PublishingHouseController;
use App\Models\Book;
use App\Models\Author;
use App\Models\PublishingHouse;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $books_count=Book::all()->count();
    $authors_count=Author::all()->count();
    $publishers_count=PublishingHouse::all()->count();
    return view('welcome', compact('books_count', 'authors_count', 'publishers_count'));
});

//Route::get('/', [IndexController::class, 'index']);

Route::resource('books', BookController::class);
Route::resource('authors', AuthorController::class);
Route::resource('publishers', PublishingHouseController::class);

resources/views/publishers/create.blade.php
@extends('layout')

@section('content')

    <style>
        .container {
            max-width: 450px;
        }
        .push-top {
            margin-top: 50px;
        }
    </style>

    <div class="card push-top">
        <div class="card-header">
            Add Author
        </div>

        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form method="post" action="{{ route('publishers.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" name="name"/>
                </div>
                <div class="form-group">
                    <label for="year_of_establishment">Year of establishment</label>
                    <input type="number" class="form-control" name="year_of_establishment"/>
                </div>
                <button type="submit" class="btn btn-block btn-danger">Create Publishing house</button>
            </form>
        </div>
    </div>
@endsection

resources/views/publishers/edit.blade.php
@extends('layout')

@section('content')

    <style>
        .container {
            max-width: 450px;
        }
        .push-top {
            margin-top: 50px;
        }
    </style>

    <div class="card push-top">
        <div class="card-header">
            Edit & Update
        </div>

        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form method="post" action="{{ route('publishers.update', $publisher->id) }}">
                @csrf
                @method('PATCH')
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" name="name" value="{{$publisher->name}}"/>
                </div>
                <div class="form-group">
                    <label for="year_of_establishment">Year of establishment</label>
                    <input type="number" class="form-control" name="year_of_establishment" value="{{$publisher->year_of_establishment}}"/>
                </div>
                <button type="submit" class="btn btn-block btn-danger">Update Publishing house</button>
            </form>
        </div>
    </div>
@endsection

resources/views/publishers/index.blade.php
@extends('layout')

@section('content')

    <style>
        .push-top {
            margin-top: 50px;
        }
    </style>

    <div class="push-top">
        @if(session()->get('completed'))
            <div class="alert alert-success">
                {{ session()->get('completed') }}
            </div><br />
        @endif
        @if($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
        @endif
        <table class="table">
            <thead>
            <tr class="table-warning">
                <td>ID</td>
                <td>Name</td>
                <td>Year of establishment</td>
                <td class="text-center">Action</td>
            </tr>
            </thead>
            <tbody>
            @foreach($publisher as $publishers)
                <tr>
                    <td>{{$publishers->id}}</td>
                    <td>{{$publishers->name}}</td>
                    <td>{{$publishers->year_of_establishment}}</td>
                    <td class="text-center">
                        <a href="{{ route('publishers.edit', $publishers->id)}}" class="btn btn-primary btn-sm">Edit</a>
                        <form action="{{ route('publishers.destroy', $publishers->id)}}" method="post" style="display: inline-block">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('Are you sure?')">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
            <a href="{{ route('publishers.create') }}" class="btn btn-primary btn-sm">Create</a>
        <div>
@endsection